version: '3.1'

services:
  db:
    image: mysql
    volumes:
      - dbbase:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: cervejaria_db

volumes:
  dbbase: